version: '3.8'

services: #описывает все контейнеры которые будут запушены
  web: #контейнер web
    build:
#      context: ./ftp # путь где брать dockerfile
      dockerfile: Dockerfile  #будет собирать контейнер из dockerfile
    ports:
      - "80:80" #делает проброс портов из 80 который в контейнере в 80 наружу
    volumes:
      - ./ftp:/home/:rw # монтирует дерикторию с правами чтение и запись

  ftp: #контейнер web
    image: delfer/alpine-ftp-server #создает контейнер с образа из dockerhub
    network_mode: host #подключает контейнер к локальной сети host
    environment: #задает переменые или условия
      - USERS=two|1234|/home/|10001 #создает пользователя two с паролем 1234 с локальной дерикторией /home с идентификатором пользователя 10001
    volumes:
      - ./ftp:/home/:rw # монтирует дерикторию 
